version: "3.4"
volumes:
  jstack-postgresql:
networks:
  default:
    driver: bridge
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5439:5432"
    volumes:
      - jstack-postgresql:/var/lib/postgresql/data
